apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openvpn-vol-claim-nfs
  namespace: vpn
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi