---
apiVersion: v1
kind: Service
metadata:
  name: openvpn
  namespace: vpn
  annotations:
    metallb.universe.tf/allow-shared-ip: "key-to-share-10.10.0.2"  
spec:
  loadBalancerIP: 10.10.0.2
  selector:
    app: openvpn
  ports:
  - name: openvpn
    targetPort: 1194
    port: 1194
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-service
  namespace: vpn
  labels:
    app: openvpn
spec:
  selector:
    app: openvpn
  ports:
    - name: metrics
      protocol: TCP
      port: 9176
      targetPort: 9176
  type: ClusterIP
