---
apiVersion: v1
kind: Service
metadata:
  name: openvpn
  namespace: eric
spec:
  selector:
    app: openvpn
  ports:
  - name: openvpn
    targetPort: 1194
    port: 1194
  type: LoadBalancer    
